# Generated by Django 4.2.5 on 2023-10-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
